name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - name: Bypass requirements.txt
      run: touch requirements.txt
    - uses: Silleellie/pylint-github-action@v1
      with:
        package-path: |
          netsubcalc
          tests
        python-version: 3.11
